# Generated by Django 3.2.4 on 2021-06-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='bkash_number',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='dob',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='nationality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='nid',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='parmanent_address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='trxid',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
